authors:
  team:
    name: PySpark Docs Team
    description: Documentation maintainers and contributors
    avatar: https://github.com/yourorg.png
  alice:
    name: Alice Smith
    description: Data engineer and PySpark contributor
    avatar: https://github.com/alicesmith.png